baseURL = "https://khalil-nouisse.github.io/portfolio/"
languageCode = 'en-us'
title = '>_ Khalil - Portfolio & Blog'
theme = 'hugo-noir' # This is the theme you are usin
# This is the theme you are using

relativeURLs = true
canonifyURLs = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false # Creates URLs like /en/blog/

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  name = ">_ Khalil"
  profile_image = "/images/profile_placeholder.jpg" # Place in your site's static/images/ directory
  email = "khalil.ait.nouisse1@gmail.com"
  github = "https://github.com/khalil-nouisse"
  github_username = "khalil-nouisse"
  linkedin = "https://www.linkedin.com/in/khalil-ait-nouisse-8ab972248/"
  linkedin_username = "khalilaitnouisse"
  twitter = "https://x.com/nouisse_ait"
  twitter_username = "nouisse_khalil"
  discord = "ait_nouisse"

[menu]
  [[menu.main]]
    name = "About Me"
    pageRef = "/about"
    weight = 1
  [[menu.main]]
    name = "Experience"
    pageRef = "/experience"
    weight = 2
  [[menu.main]]
    name = "Projects"
    pageRef = "/projects"
    weight = 3
  [[menu.main]]
    name = "Contact Me" # Note: "Contact" is used in language-specific menus above for consistency
    pageRef = "/contact"
    weight = 5 